version: "3.9"
services:
  web:
    restart: always
    build:
      context: warsey-customizer
      dockerfile: Dockerfile
      ports:
        - "7000:7000"
      volumes:
        - /usr/share/warseyapps/warseycustomizer/:/usr/share/warseyapifrontend/db/:ro